### PR TITLE
Fix map centering

### LINKED ISSUE #42: User should be able to re-center a result after scrolling away on map
Right now, if the user clicks on a marker on the map, the marker is centered.  If the user scrolls away from the marker on the map, and the marker is clicked consecutively (for a second time after scrolling), the map will not re-center the marker.

If the user clicks on a different marker after scrolling away from the previously clicked marker, it will re-center that marker.

### PR DESCRIPTION
**Pull request by bretm9**
### Participating Group Members:

- @bretm9 

### Code Highlights:

- `ResultsMap.vue`:
  - Added `resetCenter` that sets map's center to `0, 0`
  - `handleMarkerClick` invokes `resetCenter` and awaits it so data (state) is updated and component is re-rendered.

### Have Tests Been Added?

- [x] No.
- [ ] Yes, but all tests are not passing.
- [ ] Yes, and all are passing.

### Any background context you want to provide?
The component would previously not re-render (and therefore not re-center) when clicking the same marker. This is because `setSelectedMarker` wouldn't change the data's `centerMap` property (state) since it was the same value. To fix this I added `resetMap` that updates `mapCenter` to `0, 0`. I had to `await` `centerMap` in `handleMarkerClick` or else the component would still not be re-rendered since the state comparison would only be made between before and after `handleMarkerClick` was fired. `async await` makes the state comparison happen after `centerMap` evaluates and therefore the component re-renders.

### Message/Questions for reviewer:
N/A

### Issues:

- Addresses #
- Closes #42 

### Screenshots (if appropriate):
N/A

### Tracking Consistency:

- [x] added appropriate labels
- [x] My code follows the code style of this project and has removed all unnecessary annotations
- [ ] I have added comments on my pull request, particularly in hard-to-understand areas
- [x] All new and existing tests passed

- [x] looked at PR preview to check spelling, syntax, formatting, and completion

### CODE REVIEW

File: src/components/ResultsMap.vue [hunk 1]
```diff
@@ -50,7 +50,14 @@ export default {
 				};
 			}
 		},
-		handleMarkerClick(marker) {
+		resetCenter() {
```
Comment (nicolegooden) [inline src/components/ResultsMap.vue:53]: Okay, so at first the map is centered based on the user's geolocation.  Then, when the user clicks on a marker, the coordinates are reset.  I'm wondering how a latitude of 0 and a longitude of 0 affect the centering on the map.  Could you clarify why `0` has been set as the value for both?

**Review by nicolegooden — APPROVED** [review]

File: src/components/ResultsMap.vue (hunk 1 above)
Comment (stacyp2006) [reply src/components/ResultsMap.vue:53]: I have the same question, particularly since 0, 0 is a legit set of coords that land us in the Atlantic Ocean.

File: src/components/ResultsMap.vue [hunk 2]
```diff
@@ -50,7 +50,14 @@ export default {
...
+			this.centerMap = {
+				lat: 0,
+				lng: 0
+			}
+		},
+		async handleMarkerClick(marker) {
+			await this.resetCenter()
 			this.centerMapToClickedLocation(marker.name);
 			this.setSelectedMarker(marker.name);
 		},
```
Comment (stacyp2006) [inline src/components/ResultsMap.vue:63]: Nice use of async/await here.

**Review by stacyp2006 — APPROVED** [review]
Glad we got this crossed off the list. Thanks for handling it.

File: src/components/ResultsMap.vue (hunk 1 above)
Comment (npdarrington) [reply src/components/ResultsMap.vue:53]: This is definitely an interesting solution. Does that make the map snap at all before it resets with the proper coordinates?

**Review by npdarrington — APPROVED** [review]
