### PR TITLE
Bug fix for Results View

### LINKED ISSUE #151: Fix bug where user can navigate to "View Results" tab and bypass email input

### PR DESCRIPTION
**Pull request by stacyp2006**
### Participating Group Members:

- Stacy 
- Bret
- Nathan

### Code Highlights:

- This pr addresses the bug that allowed users to navigate to the `results list` with out entering their email. 
- Adds a `noEmail` property to the `data()` on `ResultsList`
- Adds conditionals to `load()` and `message()` to properly render the error message

### Have Tests Been Added?

- [x] No.
- [ ] Yes, but all tests are not passing.
- [ ] Yes, and all are passing.

### Message/Questions for reviewer:
- Do we want the loading message/animation to render if the user skips the email? Or just go straight to the error message? It does currently render. 
- I shortened the `setTimeout` to 4 seconds because 6 felt long to me, but we can change it back if needed. 

### Issues:

- Closes #151 

### Screenshots (if appropriate):
Screen Shot 2021-01-26 at 3 59 44 PM

### Tracking Consistency:

- [x] added appropriate labels
- [x] My code follows the code style of this project and has removed all unnecessary annotations
- [ ] I have added comments on my pull request, particularly in hard-to-understand areas
- [x] All new and existing tests passed
- [x] looked at PR preview to check spelling, syntax, formatting, and completion

### CODE REVIEW

File: src/components/ResultsList.vue [hunk 1]
```diff
@@ -28,38 +32,43 @@ export default {
...
-      this.sorted = true
-    }
+        return parkB.rating - parkA.rating;
+      });
+      this.sorted = true;
+    },
   },
   mounted() {
-    setTimeout(() => this.load(), 6000)
+    setTimeout(() => this.load(), 4000);
```
Comment (nicolegooden) [inline src/components/ResultsList.vue:55]: Reducing from 6 to 4 seconds is fine with me!

**Comment by nicolegooden** [comment]
Hey Stacy! Thank you for working on this.  My preference would be to show the error message immediately if the user tries to view results before signing in with the email, since the loading animation wouldn't serve a purpose in that case.

File: src/components/ResultsList.vue [hunk 2]
```diff
@@ -28,38 +32,43 @@ export default {
...
   },
   components: { ResultsListItem, FindPark, LoadingIcon },
   computed: {
     message() {
```
Comment (nicolegooden) [inline src/components/ResultsList.vue:59]: How does the loading message still show if the user doesn't have an email stored in Vuex?  From what I understand, `this.noEmail` should be true if the user visits the results too early, and shouldn't reach the second `else if` on line 65 that shows `Loading parks...`.  Am I misunderstanding, or are you referring to something else in your PR?

**Review by nicolegooden — APPROVED** [review]

File: src/components/ResultsList.vue (hunk 2 above)
Comment (nicolegooden) [reply src/components/ResultsList.vue:59]: Oh, never mind! I just remembered the `setTimeout`...

File: src/components/ResultsList.vue [hunk 3]
```diff
@@ -28,38 +32,43 @@ export default {
   data() {
     return {
       noResults: false,
-      sorted: false
-    }
+      noEmail: false,
```
Comment (npdarrington) [inline src/components/ResultsList.vue:35]: Adding another data property makes this work really well!

**Review by npdarrington — APPROVED** [review]
Thank you for finding this bug and addressing it!

**Comment by stacyp2006** [comment]
> Hey @stacyp2006 ! Thank you for working on this. My preference would be to show the error message immediately if the user tries to view results before signing in with the email, since the loading animation wouldn't serve a purpose in that case.
> 
> Do you have any ideas for how to get that error message shown immediately?

Nathan helped me with this. I thought the solution would lie in reworking the rendering in `<template>` somewhere, but Nathan pointed out that `mounted()` has the `setTimeout` which always runs. We moved the if conditional from `load()` to `mounted()` and it seems to be working in the way we want. If you agree, I think this is ready to merge.

File: src/components/ResultsList.vue [hunk 4]
```diff
@@ -28,38 +32,45 @@ export default {
...
+      this.sorted = true;
+    },
   },
   mounted() {
-    setTimeout(() => this.load(), 6000)
+    if (!this.$store.state.email) {
+      this.noEmail = true;
+    } else {
+      setTimeout(() => this.load(), 4000);
+    }
```
Comment (nicolegooden) [inline src/components/ResultsList.vue:57]: Love this!

**Review by nicolegooden — APPROVED** [review]
Thanks for adding that condition in `mounted( )`.  I will rebase and merge this PR.
