### PR TITLE
Fix search

### LINKED ISSUE #96: Search Near Me Route
When a user doesn't have location services activated, the `Find parks near me!` button should be disabled. It shouldn't be clickable and should have a different appearance.  Once the route was added, it was still clickable even with the disabled class.

### PR DESCRIPTION
**Pull request by stacyp2006**
### Participating Group Members:

- Stacy Potten

### Code Highlights:

- Add disabled class to router wrapper on `Find parks near me!` button. 
- Add disabled styling to router and separates background color to the button only. 
- Add aria label to input for better accessibility.

### Have Tests Been Added?

- [x] No.
- [ ] Yes, but all tests are not passing.
- [ ] Yes, and all are passing.

### Any background context you want to provide?
- The router sets an `<a>` tag around the `button`. If the disabled styling is applied there, the background color maintains the shape of the `<a>` tag which is slightly larger than the button. Separating it out makes the border of the button cleaner. 
- I ran the Lighthouse report and we had a score of 87. The two issues it indicated were poor contrast between the color of the disabled button and the other colors of the app and a missing label on the input. I added an aria label to the input and that brought our score up to 97.

### Message/Questions for reviewer:
- Any ideas for a better disabled color? 

### Issues:

- Addresses #
- Closes #96 

### Screenshots (if appropriate):

\*

### Tracking Consistency:

- [x] added appropriate labels
- [x] My code follows the code style of this project and has removed all unnecessary annotations
- [x] I have added comments on my pull request, particularly in hard-to-understand areas
- [ ] All new and existing tests passed
- [x] looked at PR preview to check spelling, syntax, formatting, and completion

### CODE REVIEW

File: src/components/FindPark.vue [hunk 1]
```diff
@@ -1,7 +1,10 @@
 <template>
   <section>
     <h2>Let's Go Play!</h2>
-    <router-link to='/results'>
+    <router-link
+      :class="{ disabled: !this.$store.state.geolocation }"
+      to="/results"
+    >
```
Comment (npdarrington) [inline src/components/FindPark.vue:7]: Really glad this worked! Makes the logic much easier to work with.

File: src/components/FindPark.vue [hunk 2]
```diff
@@ -13,10 +16,11 @@
     <input
       class="search-input"
       type="text"
+      aria-label="Type your search terms here"
```
Comment (npdarrington) [inline src/components/FindPark.vue:19]: Really appreciate the aria-label as I have not focused on any of that yet with the new design and styling. Thank you!

**Review by npdarrington — APPROVED** [review]
Not sure what else would be a good color to use for disabled. I think the pseudo-class for css for disabled just changes the opacity for it. We could make our own custom class to use rather than the pseudo-class if we feel it affects the accessibility score too much.

File: src/components/FindPark.vue [hunk 3]
```diff
@@ -1,7 +1,10 @@
 <template>
   <section>
     <h2>Let's Go Play!</h2>
-    <router-link to='/results'>
+    <router-link
```
Comment (bretm9) [inline src/components/FindPark.vue:4]: I'm confused why this wasn't working this morning, but I'm happy to see it working now! Maybe we were just having a syntax error before or something. This is an ideal user-experience.

File: src/components/FindPark.vue [hunk 4]
```diff
@@ -50,8 +54,8 @@ export default {
 <style lang="scss" scoped>
 @import '../styles/_mixins.scss';
 section {
-	@include customDisplayFlex(0, 0, column);
-	align-items: center;
+  @include customDisplayFlex(0, 0, column);
```
Comment (bretm9) [inline src/components/FindPark.vue:57]: Good to see the utilization of this mixin!

**Review by bretm9 — APPROVED** [review]
Thanks for getting this fixed!

File: src/components/FindPark.vue [hunk 5]
```diff
@@ -1,7 +1,10 @@
 <template>
   <section>
     <h2>Let's Go Play!</h2>
-    <router-link to='/results'>
+    <router-link
+      :class="{ disabled: !this.$store.state.geolocation }"
+      to="/results"
+    >
       <button
         :class="{ disabled: !this.$store.state.geolocation }"
```
Comment (nicolegooden) [inline src/components/FindPark.vue:9]: Do we want this button to be disabled if `geolocation` is `null`? I don't believe this part of the functionality depends on `geolocation` since the user is providing input rather than clicking the button to get nearby parks.

**Review by nicolegooden — APPROVED** [review]
Thank you for checking out our Lighthouse score for accessibility and for making the required changes to make the app more accessible in general.  Great job!
